name: CI/CD to aliyun
on:
  push:
    branches: [dev]

env:
  ALIYUN_REGION: cn-shanghai
  OSSBUCKET: oss://github-deploy-demo/deploy/
  WEBHOOK_KEY: dNELPj4HNB13cmQ98BOM

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: mkdir upload
      - run: cp app/run.sh deploy/deploy.sh  -t upload
      - run: cp data upload -r
        # no official implements,  fork from another personal project
      - uses: steven-jiang-valtech/setup-aliyun-cli-action@master
        with:
          # current version
          aliyun-cli-version: "3.0.160"
          # fix value
          mode: AK
          access-key-id: ${{ secrets.ALIYUN_APP_ID }}
          access-key-secret: ${{ secrets.ALIYUN_APP_SECRET }}
          region: ${{ env.ALIYUN_REGION }}
        # upload zip file to Aliyun's OSS Storage
      - run: aliyun oss cp ./upload  ${{env.OSSBUCKET}}  -u -r
        # call a http webhook to start pipeline, different pipeline have different KEY
      - run: 'curl -H "Content-Type: application/json" -X POST -d "{}" http://flow-openapi.aliyun.com/pipeline/webhook/${{ env.WEBHOOK_KEY }}'
